version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: myapp
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: rootpassword
        ports:
            - "8080:80"
        depends_on:
            - mysql
        restart: unless-stopped

volumes:
    mysql_data:
